"""Survey the four timetable .docx files: prove every table is visible.

For each file this reports how many tables exist, how many of them are hidden
inside content controls (and so invisible to ``Document.tables``), each
table's physical and logical dimensions, and the nearest preceding non-empty
paragraph - the division, room or faculty header the table belongs to.

It parses no cell contents. It exists to show the reader sees all the data
before any parser is trusted with it.

Run from the repo root::

    python -m ingestion.survey            # writes ingestion/survey_report.txt
    python -m ingestion.survey --stdout   # print instead
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

from ingestion.docx_reader import (
    is_sdt_wrapped,
    logical_cells,
    open_document,
    paragraph_text,
    physical_grid_width,
    walk_body,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
REAL_DIR = REPO_ROOT / "data" / "real"
DEFAULT_REPORT = Path(__file__).resolve().parent / "survey_report.txt"

SOURCE_FILES = (
    "CE_Class_Time_Table-EVEN_sem_25-26.docx",
    "CE_Class_Time_Table-ODD_sem_25-26.docx",
    "Lab CE_Time_Table-Even_sem_25-26.docx",
    "Faculty Individual timetable Even 2025-26.docx",
)


@dataclass(frozen=True)
class TableSurvey:
    index: int
    sdt_wrapped: bool
    physical_cols: int
    rows: int
    cols: int
    header: str | None
    # The non-empty paragraph before ``header``, when it also sits between the
    # previous table and this one. In the lab file the room number is here:
    # its utilisation line comes between "ROOM NO" and the table.
    above: str | None
    # True when another table sits between this one and its header paragraph,
    # i.e. the header was really written for an earlier table.
    header_shared: bool


@dataclass(frozen=True)
class FileSurvey:
    name: str
    tables: list[TableSurvey]

    @property
    def sdt_wrapped(self) -> int:
        return sum(t.sdt_wrapped for t in self.tables)


def _one_line(text: str) -> str:
    """Collapse a paragraph's tabs, runs of spaces and line breaks for display."""
    return " ".join(text.split())


def survey_file(path: Path) -> FileSurvey:
    document = open_document(path)
    tables: list[TableSurvey] = []
    # Non-empty paragraphs since the previous table, nearest last.
    since_table: list[str] = []
    last_header: str | None = None
    for kind, element in walk_body(document):
        if kind == "paragraph":
            text = _one_line(paragraph_text(element))
            if text:
                since_table.append(text)
                last_header = text
            continue
        _, n_rows, n_cols = logical_cells(element)
        tables.append(
            TableSurvey(
                index=len(tables),
                sdt_wrapped=is_sdt_wrapped(element),
                physical_cols=physical_grid_width(element),
                rows=n_rows,
                cols=n_cols,
                header=last_header,
                above=since_table[-2] if len(since_table) >= 2 else None,
                header_shared=not since_table and last_header is not None,
            )
        )
        since_table = []
    return FileSurvey(path.name, tables)


def format_report(surveys: list[FileSurvey]) -> str:
    lines = [
        "Chronos - .docx table survey (generated by `python -m ingestion.survey`)",
        "",
        "Columns: # | sdt = inside a <w:sdt> content control (invisible to Document.tables)",
        "         | physical = <w:gridCol> count | logical = rows x cols after merge resolution",
        "         | header = nearest preceding non-empty paragraph",
        "           ('(shared)' = another table sits between it and this one;",
        "            'above:' = the paragraph before it, when no table intervenes)",
        "",
    ]
    for s in surveys:
        lines.append("=" * 78)
        lines.append(s.name)
        lines.append(
            f"  tables found: {len(s.tables)}   sdt-wrapped: {s.sdt_wrapped}   "
            f"visible to Document.tables: {len(s.tables) - s.sdt_wrapped}"
        )
        lines.append("")
        for t in s.tables:
            header = t.header if t.header is not None else "<none>"
            if t.header_shared:
                header = f"(shared) {header}"
            lines.append(
                f"  {t.index:>2} | {'sdt' if t.sdt_wrapped else '   '} | "
                f"physical {t.physical_cols:>2} | logical {t.rows:>2} x {t.cols:<2} | {header}"
            )
            if t.above is not None:
                lines.append(f"{'':>45}above: {t.above}")
        lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=DEFAULT_REPORT, help="report path")
    parser.add_argument("--stdout", action="store_true", help="print instead of writing")
    args = parser.parse_args(argv)

    report = format_report([survey_file(REAL_DIR / name) for name in SOURCE_FILES])
    if args.stdout:
        print(report)
    else:
        args.out.write_text(report, encoding="utf-8")
        print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
