"""initial schema

Revision ID: 1c8c78738a94
Revises: 
Create Date: 2026-09-24 13:00:09.895735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c8c78738a94'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institute')),
    sa.UniqueConstraint('code', name=op.f('uq_institute_code'))
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institute.id'], name=op.f('fk_department_institute_id_institute')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department')),
    sa.UniqueConstraint('institute_id', 'code', name='uq_department_institute_code')
    )
    op.create_index(op.f('ix_department_institute_id'), 'department', ['institute_id'], unique=False)
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('used_as', sa.Enum('class', 'lab', 'unknown', name='room_used_as'), nullable=False),
    sa.Column('separation', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['institute_id'], ['institute.id'], name=op.f('fk_room_institute_id_institute')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room'))
    )
    op.create_index(op.f('ix_room_code'), 'room', ['code'], unique=False)
    op.create_index(op.f('ix_room_institute_id'), 'room', ['institute_id'], unique=False)
    op.create_table('audit_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('affected_session_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detail', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_audit_entry_department_id_department')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_entry'))
    )
    op.create_index(op.f('ix_audit_entry_action'), 'audit_entry', ['action'], unique=False)
    op.create_index(op.f('ix_audit_entry_actor'), 'audit_entry', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_entry_department_id'), 'audit_entry', ['department_id'], unique=False)
    op.create_index(op.f('ix_audit_entry_timestamp'), 'audit_entry', ['timestamp'], unique=False)
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('initials', sa.String(length=16), nullable=True),
    sa.Column('theory_hours', sa.Integer(), nullable=True),
    sa.Column('practical_hours', sa.Integer(), nullable=True),
    sa.Column('total_hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_faculty_department_id_department')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faculty'))
    )
    op.create_index(op.f('ix_faculty_department_id'), 'faculty', ['department_id'], unique=False)
    op.create_index(op.f('ix_faculty_initials'), 'faculty', ['initials'], unique=False)
    op.create_table('programme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_programme_department_id_department')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programme')),
    sa.UniqueConstraint('department_id', 'code', name='uq_programme_department_code')
    )
    op.create_index(op.f('ix_programme_department_id'), 'programme', ['department_id'], unique=False)
    op.create_table('sub_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('fk_sub_room_room_id_room'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sub_room')),
    sa.UniqueConstraint('room_id', 'label', name='uq_sub_room_room_label')
    )
    op.create_index(op.f('ix_sub_room_room_id'), 'sub_room', ['room_id'], unique=False)
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('session_type', sa.Enum('theory', 'lab', 'both', name='subject_session_type'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_subject_department_id_department')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject')),
    sa.UniqueConstraint('department_id', 'code', name='uq_subject_department_code')
    )
    op.create_index(op.f('ix_subject_department_id'), 'subject', ['department_id'], unique=False)
    op.create_table('absence_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('absence_date', sa.Date(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('replacement_faculty_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day >= 0 AND day <= 4', name=op.f('ck_absence_record_day_range')),
    sa.CheckConstraint('period >= 0 AND period <= 9', name=op.f('ck_absence_record_period_range')),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_absence_record_department_id_department')),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], name=op.f('fk_absence_record_faculty_id_faculty')),
    sa.ForeignKeyConstraint(['replacement_faculty_id'], ['faculty.id'], name=op.f('fk_absence_record_replacement_faculty_id_faculty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_absence_record'))
    )
    op.create_index(op.f('ix_absence_record_department_id'), 'absence_record', ['department_id'], unique=False)
    op.create_index(op.f('ix_absence_record_faculty_id'), 'absence_record', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_absence_record_replacement_faculty_id'), 'absence_record', ['replacement_faculty_id'], unique=False)
    op.create_table('qualification',
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('observed', 'declared', name='qualification_source'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], name=op.f('fk_qualification_faculty_id_faculty'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_qualification_subject_id_subject'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('faculty_id', 'subject_id', name=op.f('pk_qualification'))
    )
    op.create_table('semester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('term_code', sa.Enum('ODD', 'EVEN', name='term_code'), nullable=False),
    sa.Column('academic_year', sa.String(length=16), nullable=False),
    sa.CheckConstraint('number >= 1 AND number <= 10', name=op.f('ck_semester_number_range')),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_semester_department_id_department')),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], name=op.f('fk_semester_programme_id_programme')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semester')),
    sa.UniqueConstraint('programme_id', 'number', 'academic_year', name='uq_semester_programme_number_year')
    )
    op.create_index(op.f('ix_semester_department_id'), 'semester', ['department_id'], unique=False)
    op.create_index(op.f('ix_semester_programme_id'), 'semester', ['programme_id'], unique=False)
    op.create_table('cohort',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('cohort_type', sa.Enum('division', 'batch', 'elective', 'combined', name='cohort_type'), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("cohort_type <> 'batch' OR division_id IS NOT NULL", name=op.f('ck_cohort_batch_requires_division')),
    sa.CheckConstraint("cohort_type <> 'division' OR semester_id IS NOT NULL", name=op.f('ck_cohort_division_requires_semester')),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_cohort_department_id_department')),
    sa.ForeignKeyConstraint(['division_id'], ['cohort.id'], name=op.f('fk_cohort_division_id_cohort')),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], name=op.f('fk_cohort_semester_id_semester')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cohort'))
    )
    op.create_index(op.f('ix_cohort_cohort_type'), 'cohort', ['cohort_type'], unique=False)
    op.create_index(op.f('ix_cohort_department_id'), 'cohort', ['department_id'], unique=False)
    op.create_index(op.f('ix_cohort_division_id'), 'cohort', ['division_id'], unique=False)
    op.create_index(op.f('ix_cohort_label'), 'cohort', ['label'], unique=False)
    op.create_index(op.f('ix_cohort_semester_id'), 'cohort', ['semester_id'], unique=False)
    op.create_table('timetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'generated', 'published', 'archived', 'observed', name='timetable_status'), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('algorithm', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_timetable_department_id_department')),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], name=op.f('fk_timetable_semester_id_semester')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timetable'))
    )
    op.create_index(op.f('ix_timetable_department_id'), 'timetable', ['department_id'], unique=False)
    op.create_index(op.f('ix_timetable_semester_id'), 'timetable', ['semester_id'], unique=False)
    op.create_table('cohort_batch_membership',
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['cohort.id'], name=op.f('fk_cohort_batch_membership_batch_id_cohort'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohort.id'], name=op.f('fk_cohort_batch_membership_cohort_id_cohort'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cohort_id', 'batch_id', name=op.f('pk_cohort_batch_membership'))
    )
    op.create_table('cohort_division_membership',
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohort.id'], name=op.f('fk_cohort_division_membership_cohort_id_cohort'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['division_id'], ['cohort.id'], name=op.f('fk_cohort_division_membership_division_id_cohort'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cohort_id', 'division_id', name=op.f('pk_cohort_division_membership'))
    )
    op.create_table('lab_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('start_period', sa.Integer(), nullable=False),
    sa.Column('duration_periods', sa.Integer(), nullable=False),
    sa.Column('must_be_contiguous', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('day >= 0 AND day <= 4', name=op.f('ck_lab_block_day_range')),
    sa.CheckConstraint('duration_periods >= 1', name=op.f('ck_lab_block_duration_positive')),
    sa.CheckConstraint('start_period >= 0 AND start_period <= 9', name=op.f('ck_lab_block_start_period_range')),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_lab_block_department_id_department')),
    sa.ForeignKeyConstraint(['division_id'], ['cohort.id'], name=op.f('fk_lab_block_division_id_cohort')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_block'))
    )
    op.create_index(op.f('ix_lab_block_department_id'), 'lab_block', ['department_id'], unique=False)
    op.create_index(op.f('ix_lab_block_division_id'), 'lab_block', ['division_id'], unique=False)
    op.create_table('pinned_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('cohort_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('duration_periods', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('mdm', 'hss', 'llc', 'activity', 'project', 'exam', 'break', name='pinned_kind'), nullable=False),
    sa.CheckConstraint('day >= 0 AND day <= 4', name=op.f('ck_pinned_block_day_range')),
    sa.CheckConstraint('duration_periods >= 1', name=op.f('ck_pinned_block_duration_positive')),
    sa.CheckConstraint('period >= 0 AND period <= 9', name=op.f('ck_pinned_block_period_range')),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohort.id'], name=op.f('fk_pinned_block_cohort_id_cohort')),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_pinned_block_department_id_department')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pinned_block'))
    )
    op.create_index(op.f('ix_pinned_block_cohort_id'), 'pinned_block', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_pinned_block_department_id'), 'pinned_block', ['department_id'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('sub_room_id', sa.Integer(), nullable=True),
    sa.Column('lab_block_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('duration_periods', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.Enum('theory', 'lab', name='session_type'), nullable=False),
    sa.Column('source_cell', sa.String(length=512), nullable=True),
    sa.CheckConstraint('NOT (room_id IS NOT NULL AND sub_room_id IS NOT NULL)', name=op.f('ck_session_room_xor_sub_room')),
    sa.CheckConstraint('day >= 0 AND day <= 4', name=op.f('ck_session_day_range')),
    sa.CheckConstraint('duration_periods >= 1', name=op.f('ck_session_duration_positive')),
    sa.CheckConstraint('period >= 0 AND period <= 9', name=op.f('ck_session_period_range')),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohort.id'], name=op.f('fk_session_cohort_id_cohort')),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_session_department_id_department')),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], name=op.f('fk_session_faculty_id_faculty')),
    sa.ForeignKeyConstraint(['lab_block_id'], ['lab_block.id'], name=op.f('fk_session_lab_block_id_lab_block'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('fk_session_room_id_room')),
    sa.ForeignKeyConstraint(['sub_room_id'], ['sub_room.id'], name=op.f('fk_session_sub_room_id_sub_room')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_session_subject_id_subject')),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetable.id'], name=op.f('fk_session_timetable_id_timetable'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session'))
    )
    op.create_index(op.f('ix_session_cohort_id'), 'session', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_session_department_id'), 'session', ['department_id'], unique=False)
    op.create_index(op.f('ix_session_faculty_id'), 'session', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_session_lab_block_id'), 'session', ['lab_block_id'], unique=False)
    op.create_index(op.f('ix_session_room_id'), 'session', ['room_id'], unique=False)
    op.create_index(op.f('ix_session_sub_room_id'), 'session', ['sub_room_id'], unique=False)
    op.create_index(op.f('ix_session_subject_id'), 'session', ['subject_id'], unique=False)
    op.create_index(op.f('ix_session_timetable_id'), 'session', ['timetable_id'], unique=False)
    # --- HAND-ADDED (not produced by autogenerate) ---------------------------
    # A composite primary key (a, b) gives Postgres one btree index ordered by
    # a, so a lookup filtering on b alone cannot use it. Autogenerate never
    # adds these. Each is a query this project actually runs:
    #   qualification.subject_id  -> "who else is qualified to teach X?", the
    #                                candidate query behind substitution
    #   *_membership trailing col -> "which cohorts contain this division or
    #                                batch?", used to derive COHORT edges
    op.create_index(
        op.f("ix_qualification_subject_id"), "qualification", ["subject_id"], unique=False
    )
    op.create_index(
        op.f("ix_cohort_division_membership_division_id"),
        "cohort_division_membership",
        ["division_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cohort_batch_membership_batch_id"),
        "cohort_batch_membership",
        ["batch_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # --- HAND-ADDED: reverse of the indexes added at the end of upgrade() ---
    op.drop_index(
        op.f("ix_cohort_batch_membership_batch_id"), table_name="cohort_batch_membership"
    )
    op.drop_index(
        op.f("ix_cohort_division_membership_division_id"),
        table_name="cohort_division_membership",
    )
    op.drop_index(op.f("ix_qualification_subject_id"), table_name="qualification")
    op.drop_index(op.f('ix_session_timetable_id'), table_name='session')
    op.drop_index(op.f('ix_session_subject_id'), table_name='session')
    op.drop_index(op.f('ix_session_sub_room_id'), table_name='session')
    op.drop_index(op.f('ix_session_room_id'), table_name='session')
    op.drop_index(op.f('ix_session_lab_block_id'), table_name='session')
    op.drop_index(op.f('ix_session_faculty_id'), table_name='session')
    op.drop_index(op.f('ix_session_department_id'), table_name='session')
    op.drop_index(op.f('ix_session_cohort_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_pinned_block_department_id'), table_name='pinned_block')
    op.drop_index(op.f('ix_pinned_block_cohort_id'), table_name='pinned_block')
    op.drop_table('pinned_block')
    op.drop_index(op.f('ix_lab_block_division_id'), table_name='lab_block')
    op.drop_index(op.f('ix_lab_block_department_id'), table_name='lab_block')
    op.drop_table('lab_block')
    op.drop_table('cohort_division_membership')
    op.drop_table('cohort_batch_membership')
    op.drop_index(op.f('ix_timetable_semester_id'), table_name='timetable')
    op.drop_index(op.f('ix_timetable_department_id'), table_name='timetable')
    op.drop_table('timetable')
    op.drop_index(op.f('ix_cohort_semester_id'), table_name='cohort')
    op.drop_index(op.f('ix_cohort_label'), table_name='cohort')
    op.drop_index(op.f('ix_cohort_division_id'), table_name='cohort')
    op.drop_index(op.f('ix_cohort_department_id'), table_name='cohort')
    op.drop_index(op.f('ix_cohort_cohort_type'), table_name='cohort')
    op.drop_table('cohort')
    op.drop_index(op.f('ix_semester_programme_id'), table_name='semester')
    op.drop_index(op.f('ix_semester_department_id'), table_name='semester')
    op.drop_table('semester')
    op.drop_table('qualification')
    op.drop_index(op.f('ix_absence_record_replacement_faculty_id'), table_name='absence_record')
    op.drop_index(op.f('ix_absence_record_faculty_id'), table_name='absence_record')
    op.drop_index(op.f('ix_absence_record_department_id'), table_name='absence_record')
    op.drop_table('absence_record')
    op.drop_index(op.f('ix_subject_department_id'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_sub_room_room_id'), table_name='sub_room')
    op.drop_table('sub_room')
    op.drop_index(op.f('ix_programme_department_id'), table_name='programme')
    op.drop_table('programme')
    op.drop_index(op.f('ix_faculty_initials'), table_name='faculty')
    op.drop_index(op.f('ix_faculty_department_id'), table_name='faculty')
    op.drop_table('faculty')
    op.drop_index(op.f('ix_audit_entry_timestamp'), table_name='audit_entry')
    op.drop_index(op.f('ix_audit_entry_department_id'), table_name='audit_entry')
    op.drop_index(op.f('ix_audit_entry_actor'), table_name='audit_entry')
    op.drop_index(op.f('ix_audit_entry_action'), table_name='audit_entry')
    op.drop_table('audit_entry')
    op.drop_index(op.f('ix_room_institute_id'), table_name='room')
    op.drop_index(op.f('ix_room_code'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_department_institute_id'), table_name='department')
    op.drop_table('department')
    op.drop_table('institute')
    # ### end Alembic commands ###

    # --- HAND-ADDED (autogenerate defect, verified empirically) --------------
    # sa.Enum() inside create_table makes Postgres CREATE TYPE implicitly, but
    # drop_table does NOT drop the type. Without this loop, `downgrade base`
    # leaves all eight enum types orphaned and the next `upgrade head` dies
    # with: DuplicateObject: type "room_used_as" already exists.
    for enum_name in (
        "cohort_type",
        "pinned_kind",
        "qualification_source",
        "room_used_as",
        "session_type",
        "subject_session_type",
        "term_code",
        "timetable_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
